# encoding: utf-8
Gem::Specification.new do |spec|
  spec.name          = "minimal-mistakes-jekyll"
  spec.version       = "4.24.0"
  spec.authors       = ["Michael Rose"]
  spec.email         = ["michael@michaelrose.me"]

  spec.summary       = %q{Minimal Mistakes is a flexible two column Jekyll theme.}
  spec.description   = %q{Minimal Mistakes is a flexible two column Jekyll theme.}
  spec.homepage      = "https://github.com/mmistakes/minimal-mistakes"
  spec.license       = "MIT"

  spec.files         = Dir["{*,_layouts,_includes,_sass,assets}/**/*", "LICENSE", "README.md", "minimal-mistakes.gemspec"]
  spec.require_paths = ["lib"]

  spec.add_runtime_dependency "jekyll", "~> 4.0"
  spec.add_runtime_dependency "jekyll-sitemap", "~> 1.4"
  spec.add_development_dependency "rake", "~> 13.0"
end
